export function ArticleBody({ content }: { content: string }) {
  if (!content.trim()) return null;

  return (
    <div
      className="site-rich-text mx-auto max-w-[860px] text-[17px] font-normal leading-[1.85] text-white/72 [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&_a]:font-semibold [&_a]:text-[#d9b86e] [&_a]:underline [&_a]:decoration-[#d9b86e]/40 [&_a]:underline-offset-4 [&_a]:transition-colors [&_a:hover]:text-[#dec17c] [&_blockquote]:my-10 [&_blockquote]:rounded-r-xl [&_blockquote]:border-l-4 [&_blockquote]:border-[#d9b86e] [&_blockquote]:bg-[#211f1b] [&_blockquote]:py-4 [&_blockquote]:pl-6 [&_blockquote]:pr-5 [&_blockquote]:text-lg [&_blockquote]:font-medium [&_blockquote]:italic [&_blockquote]:text-white/82 [&_code]:rounded [&_code]:bg-white/8 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-[0.9em] [&_code]:text-[#dec17c] [&_figcaption]:mt-3 [&_figcaption]:text-center [&_figcaption]:text-sm [&_figcaption]:leading-6 [&_figcaption]:text-white/48 [&_figure]:my-12 [&_h2]:mb-5 [&_h2]:mt-14 [&_h2]:scroll-mt-[100px] [&_h2]:font-sans [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:leading-tight [&_h2]:tracking-[-0.02em] [&_h2]:text-white sm:[&_h2]:text-3xl [&_h3]:mb-4 [&_h3]:mt-11 [&_h3]:scroll-mt-[100px] [&_h3]:font-sans [&_h3]:text-xl [&_h3]:font-bold [&_h3]:leading-tight [&_h3]:tracking-[-0.015em] [&_h3]:text-white sm:[&_h3]:text-2xl [&_h4]:mb-3 [&_h4]:mt-9 [&_h4]:scroll-mt-[100px] [&_h4]:font-sans [&_h4]:text-lg [&_h4]:font-bold [&_h4]:text-white [&_hr]:my-12 [&_hr]:border-white/10 [&_img]:my-11 [&_img]:block [&_img]:h-auto [&_img]:w-full [&_img]:rounded-xl [&_img]:border-2 [&_img]:border-solid [&_img]:border-white/20 [&_li]:my-2 [&_li]:pl-1 [&_ol]:my-7 [&_ol]:list-decimal [&_ol]:space-y-2.5 [&_ol]:pl-7 [&_ol]:marker:font-semibold [&_ol]:marker:text-[#d9b86e] [&_p]:my-5 [&_pre]:my-9 [&_pre]:overflow-x-auto [&_pre]:rounded-xl [&_pre]:bg-[#0d0c0b] [&_pre]:p-5 [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_strong]:font-bold [&_strong]:text-white/92 [&_table]:my-9 [&_table]:block [&_table]:w-full [&_table]:overflow-x-auto [&_table]:border-collapse [&_td]:border [&_td]:border-white/10 [&_td]:p-3 [&_th]:border [&_th]:border-white/10 [&_th]:bg-white/5 [&_th]:p-3 [&_th]:text-left [&_th]:text-white [&_ul]:my-7 [&_ul]:list-disc [&_ul]:space-y-2.5 [&_ul]:pl-7 [&_ul]:marker:text-[#d9b86e] sm:text-lg"
      dangerouslySetInnerHTML={{ __html: content }}
    />
  );
}
